---
# Ez az app-server Ansible role fő file-ja. A role_action változó értéke szerint dönt, hogy melyik playbook-ot hívja meg.

- name: Provision the app server
  include_tasks: provision.yml
  when:
    - role_action == "provision"

- name: Deploy the application
  include_tasks: deploy-app.yml
  when:
    - role_action == "deploy" or role_action == "provision"

...
