---
# This workflow runs when the master branch changes. 
# An Anisble playbook will be executed on the Inferno RPG server to stop the service, update the code and start the service again.

name: CD

on:
  pull_request:
    branches:
      - master
    types:
      - closed

# Steve
jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write SSH file
        env:
          SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa

      - name: Write Inventory file
        env:
          INVENTORY: ${{ secrets.PRODUCTION_INVENTORY }}
        run: echo "$INVENTORY" > inventory

      - name: Deploy to Production with Ansible
        run: 'ansible-playbook -v -i inventory --extra-vars "role_action=deploy app_environment=production discord_token=${{ secrets.PRODUCTION_DISCORD_TOKEN }}" manage-app-server.yml'
