---
# This action should run only when a feature branch is merged to the master branch

name: CD

on:
  pull_request:
    branches:
      - master
    types:
      - closed

# Steve
jobs:
  build-and-push-docker-image:
    # CD Conditions
    # Only run when a pull request is merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with the "latest" tag
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:app"
          push: true
          tags: donbattery/inferno-rpg:latest

  deploy-to-staging:
    needs: [build-and-push-docker-image]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write SSH file
        env:
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa

      - name: Write Inventory file
        env:
          INVENTORY: ${{ secrets.STAGING_INVENTORY }}
        run: echo "$INVENTORY" > inventory

      - name: Deploy to Staging with Ansible
        run: "ansible-playbook -v -i inventory --extra-vars \"role_action=deploy discord_token=$DISCORD_TOKEN\" manage-app-server.yml"
