---

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches:
      - 'master'
    types:
      - closed

# Steve
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker tag to test (Staging environment)
        if: github.event_name == 'push'
        run: echo "DOCKER_TAG=test" >> $GITHUB_ENV

      - name: Set Docker tag to latest (Production environment)
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:app"
          push: true
          tags: donbattery/inferno-rpg:${{ env.DOCKER_TAG }}

  deploy-to-AWS:
    needs: [build-and-push-docker-image]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Write SSH file
        env:
          SSH_KEY: ${{ secrets.ANSIBLE_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Set up JQ
        run: sudo apt-get install jq

      - name: Write Inventory file
        run: ./create_inventory.sh > inventory

      - name: Debug inventory file
        run: |
          cat inventory
          type ansible
          ansible --version
          type ansible-playbook
          ansible-playbook --version
          type ansible-inventory
          ansible-inventory --version
          ansible-inventory --list -i inventory
        shell: bash

      - name: Set Discord token for Staging environment
        if: github.event_name == 'push'
        run: |
          echo "DISCORD_TOKEN=${{ secrets.STAGING_DISCORD_TOKEN }}" >> $GITHUB_ENV
          echo "CONTAINER_NAME=inferno-rpg-staging" >> $GITHUB_ENV
          echo "CONTAINER_IMAGE_TAG=test" >> $GITHUB_ENV

      - name: Set Discord token for Production environment
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          echo "DISCORD_TOKEN=${{ secrets.PRODUCTION_DISCORD_TOKEN }}" >> $GITHUB_ENV
          echo "CONTAINER_NAME=inferno-rpg-production" >> $GITHUB_ENV
          echo "CONTAINER_IMAGE_TAG=latest" >> $GITHUB_ENV

      - name: Deploy to AWS with Ansible
        run: 'ansible-playbook -v -i inventory --extra-vars "role_action=deploy discord_token=${{ env.DISCORD_TOKEN }} container_name={{ env.CONTAINER_NAME }} container_iamge_tag={{ env.CONTAINER_IMAGE_TAG }}" manage-app-server.yml'

...
