---
# Ez az akció akkor fut ha egy brencset belemerdzseltek a mászterbe.
# Megbuildeli az alkalmazás Docker képét és felpusholja a Docker hub-ra, a latest teggel.
# Utána megkeresi az AWS-en az inferno-rpg-server nevű EC2 gépet, és betelefonál,
# hogy ugyan futtassa most már a latest image-ból az inferno-rpg Docker konténert.

name: Deployment

on:
  pull_request:
    branches:
      - master
    types:
      - closed

# Steve
jobs:
  build-and-push-docker-image:
    # CD Conditions
    # Only run when a pull request is merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with the "latest" tag
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:app"
          push: true
          tags: donbattery/inferno-rpg:latest

  deploy-to-AWS:
    needs: [build-and-push-docker-image]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write SSH file
        env:
          SSH_KEY: ${{ secrets.ANSIBLE_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Set up JQ
        run: sudo apt-get install jq

      - name: Write Inventory file
        run: ./create_inventory.sh > inventory

      - name: Debug inventory file
        run: |
          cat inventory
          ansible-inventory --list -i inventory
        shell: bash

      - name: Deploy to Staging with Ansible
        run: 'ansible-playbook -v -i inventory --extra-vars "role_action=deploy discord_token=${{ secrets.DISCORD_TOKEN }}" manage-app-server.yml'
