---
# Ez a folyamat minden branch változtatásnál megfut kivéve ha a master változik.
# Elvben ez felelős azért, hogy ne kerülhessen hibás kód a master-re.
# Csak olyan pull request-et szabad mergelni, amin kizöldült ez a folyamat.

name: Teszt

on:
  push:
    branches-ignore:
      - master

jobs:
  docker-test:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with the "test" tag
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:app"
          push: true
          tags: donbattery/inferno-rpg:test
